version: "3"
services:
  web-app-development:
   command: python /opt/code/bin/start_dev.py
   build:
    context: .
    dockerfile: Dockerfile_dev
   ports:
    - "8001:8000"
   volumes:
    - ".:/opt/code"
 
  nginx:
    image: nginx
    ports:
     - "80:80"
    volumes:
     - "./nginx_conf/nginx.conf:/etc/nginx/nginx.conf"
    depends_on:
     - web-app-development
