version: "3"
services:
  web-app-dev:
   command: python /opt/code/bin/start_dev.py
   build:
    context: .
    dockerfile: Dockerfile_dev
   working_dir: /opt/code/recipes_project
   ports:
    - "8001:8000"
   volumes:
    - ".:/opt/code"
 
